export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_DEVELOPER='ADD_DEVELOPER';
export const ADD_TECHNOLOGY='ADD_TECHNOLOGY';